---

- hosts: localhost
  connection: local
  vars:
    neovim_dest_dir: "{{ ansible_user_dir }}/soft"
    neovim_bin: "{{ ansible_user_dir }}/bin/nvim"
    golang_version: "1.12"
    keyboard_repeat_rate: 60
    keyboard_delay: 200
  tasks:
    - import_role: name=rpmfusion
      tags: packages

    - import_role: name=packages
      tags: packages

    - import_role: name=fonts
      tags: fonts

    - import_role: name=keyboard
      tags: keyboard

    - import_role: name=terminal
      tags: terminal

    - import_role: name=dropbox
      tags: dropbox

    - import_role: name=golang
      tags: golang

    - import_role: name=i3-mate
      tags: i3

    - import_role: name=neovim
      tags: vim

    - import_role: name=dotfiles
      tags: dotfiles

    - import_role: name=docker
      tags: docker

    - import_role: name=gcloud
      tags: gcloud

    - name: Disable SELinux
      become: yes
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
      tags: system

      # terraform
