---
- hosts: all
  tasks:
    - import_role: name=rpmfusion
      tags: rpmfusion
      when: ansible_distribution == "Fedora"

    - import_role: name=packages
      tags: packages

    - import_role: name=desktop
      tags: desktop
      when: host_mode == "home"

    - import_role: name=ssh-agent
      tags: ssh

    - import_role: name=dotfiles
      tags: dotfiles

    - import_role: name=neovim
      tags: vim

    - import_role: name=dropbox
      tags: dropbox
      when: host_mode == "home"

    - import_role: name=golang
      tags: golang
      when: host_mode == "home"

    - import_role: name=vscode
      tags: vscode
      when: host_mode == "home"

    - import_role: name=docker
      tags: docker

  # - import_role: name=gcloud
  #   tags: gcloud

  # - import_role: name=clickhouse-client
  #   tags: clickhouse

    - name: Disable SELinux
      become: yes
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
      tags: system
      when: ansible_distribution == "Fedora" or host_mode == "home"
