---

- hosts: localhost
  connection: local
  vars:
    neovim_dest_dir: "{{ ansible_user_dir }}/soft"
    neovim_bin: "{{ ansible_user_dir }}/bin/nvim"
    golang_version: "1.12"
    keyboard_repeat_rate: 60
    keyboard_delay: 200
  tasks:
    - include_role: name=rpmfusion
    - include_role: name=packages
    - include_role: name=fonts
    - include_role: name=keyboard
    - include_role: name=terminal
    - include_role: name=dropbox
    - include_role: name=golang
    - include_role: name=i3-mate
    - include_role: name=neovim
    - include_role: name=dotfiles
    - include_role:
        name: docker
        apply:
          become: yes

    - include_role:
        name: gcloud
        apply:
          become: yes

    - name: Disable SELinux
      become: yes
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'

      # gcloud, kubectl, terraform
