---
- name: Configure keyboard settings
  command: dconf write {{ item }}
  loop:
    - /org/mate/desktop/peripherals/keyboard/rate {{ desktop_keyboard_repeat_rate }}
    - /org/mate/desktop/peripherals/keyboard/delay {{ desktop_keyboard_delay }}
    - /org/mate/desktop/peripherals/keyboard/indicator/foreground-color "'{{ desktop_keyboard_indicator_foreground_color }}'"

  # XXX: I wasn't able to make it work via dconf write, so doing it via
  # gsettings
- name: Set keyboard options via gsettings
  command: gsettings set org.mate.peripherals-keyboard-xkb.kbd options "{{ desktop_keyboard_options }}"

- name: Special configuration for Macbook keyboard
  copy:
    content: "options hid_apple fnmode=2 swap_opt_cmd=1\n"
    dest: /etc/modprobe.d/hid_apple.conf
  become: yes
  notify:
    - reload hid_apple
    - rebuild initramfs
  when: "'macbook' in (ansible_product_name | lower)"

