---
- name: Ensure bin path
  file:
    state: directory
    path: "{{ packages_bin_path }}"

- name: Install bin
  get_url:
    url: "{{ packages_bin_url }}"
    dest: "{{ packages_bin_path }}/bin"
    mode: 0755
  become: yes

- name: Install binaries
  command: "{{ packages_bin_path }}/bin install {{ item }}"
  loop: "{{ packages_bin_binaries }}"
