---
- name: Import GPG keys
  rpm_key:
    key: "{{ item }}"
  loop: "{{ packages_gpg_keys }}"
  become: yes

- name: Install packages
  dnf:
    name: "{{ packages_system }}"
    state: latest
  become: yes

- name: Install python packages
  command: pipx upgrade {{ item }}
  loop: "{{ packages_python }}"
