---
- name: Import GPG keys
  rpm_key:
    key: "{{ item }}"
  loop: "{{ packages_gpg_keys }}"
  become: yes

- name: Install packages
  dnf:
    name: "{{ packages_system }}"
    state: latest
  become: yes

- name: Install pip packages
  pip:
    name: "{{ packages_pip }}"
    state: latest
    extra_args: --user
