---
- name: Ensure dev dir
  file:
    path: "{{ dotfiles_path | dirname }}"
    state: directory

- name: Ensure dotfiles git repo
  git:
    repo: "git@github.com:dzeban/dotfiles.git"
    dest: "{{ dotfiles_path }}"
    update: no
    recursive: true

- import_tasks: redshift.yml
  when: ansible_distribution == "Ubuntu"

- name: Run homemmaker
  command: make {{ host_mode }}
  args:
    chdir: "{{ dotfiles_path }}"
