---
- name: Clone dotfile git repo
  git:
    repo: git@github.com:dzeban/dotfiles.git
    dest: "{{ ansible_user_dir }}/.dotfiles"
    update: no

- name: Deploy dotfiles
  shell: "yes | make"
  args:
    chdir: "{{ ansible_user_dir }}/.dotfiles"
