---
- name: Deploy simple dotfiles
  include_tasks: files.yml
  loop: "{{ dotfiles_config }}"
  when: item.type is undefined or item.type == "file"

- name: Deploy templates
  include_tasks: templates.yml
  loop: "{{ dotfiles_config }}"
  when: "(item.type | default('file'))== 'template'"

- name: Deploy directories
  include_tasks: dirs.yml
  loop: "{{ dotfiles_config }}"
  when: "(item.type | default('file'))== 'dir'"
