---
- name: Ensure {{ item.dst | dirname }} directory
  file:
    path: "{{ item.dst | dirname }}"
    state: directory

- name: Render {{ item.dst }} dotfile
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    mode: "{{ item.mode | default('0644') }}"
