---
- name: Import vscode repo GPG key
  yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: "{{ vscode_repo_url }}"
    gpgcheck: yes
    gpgkey: "{{ vscode_repo_key }}"
  become: yes

- name: Install vscode
  dnf:
    name: code
    state: latest
  become: yes
