---

gcloud_repo: "https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64"
gcloud_gpg_keys:
  - "https://packages.cloud.google.com/yum/doc/yum-key.gpg"
  - "https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
