---
- name: Ensure install directory
  file:
    path: "{{ terraform_install_dir }}"
    state: directory

- name: Download archive
  get_url:
    url: "{{ terraform_download_url }}"
    dest: "{{ terraform_download_dir }}"
  register: archive

- name: Unpack archive
  unarchive:
    src: "{{ archive.dest }}"
    dest: "{{ terraform_install_dir }}"
  when: archive.changed or terraform_install_force
