---
- name: Configure keyboard options
  command: gsettings set org.mate.peripherals-keyboard-xkb.kbd options "{{ keyboard_options }}"

- name: Special configuration for Macbook keyboard
  copy:
    content: "options hid_apple fnmode=2 swap_opt_cmd=1\n"
    dest: /etc/modprobe.d/hid_apple.conf
  become: yes
  notify:
    - reload hid_apple
    - rebuild initramfs
  when: "{{ 'macbook' in (ansible_product_name | lower) }}"

- name: Change foreground for keyboard indicator
  command: gsettings set org.mate.peripherals-keyboard-xkb.indicator foreground-color "{{ keyboard_indicator_foreground_color }}"

- name: Configure keyboard repeat rate
  command: dconf write /org/mate/desktop/peripherals/keyboard/rate {{ keyboard_repeat_rate }}

- name: Configure keyboard delay
  command: dconf write /org/mate/desktop/peripherals/keyboard/delay {{ keyboard_delay }}
