---

- name: Add repo
  yum_repository:
    name: gcloud
    description: Google Cloud SDK
    baseurl: "{{ gcloud_repo }}"
    gpgcheck: yes
    gpgkey: "{{ gcloud_gpg_keys }}"

- name: Install google-cloud-sdk
  dnf:
    name: ["google-cloud-sdk", "kubectl"]
    state: present
