# .bashrc

# Source global definitions
[[ -f /etc/bashrc ]] && source /etc/bashrc

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

export LANG=en_US.utf8
command -v alacritty > /dev/null && export TERMINAL=alacritty

export HISTSIZE=
export HISTFILESIZE=

export PAGER=less
export EDITOR=vim
export VISUAL=vim

complete -cf sudo
shopt -s cdspell autocd dirspell globstar histappend
set show-all-if-ambigious on

# Prompt configuration
[[ -f /usr/share/git-core/contrib/completion/git-prompt.sh ]] && source /usr/share/git-core/contrib/completion/git-prompt.sh
GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWSTASHSTATE=1

__gcloud_ps1()
{
    # If gcloud is not configured return empty string
    [[ -f ~/.config/gcloud/active_config ]] || return

    local CONTEXT=$(cat ~/.config/gcloud/active_config)
    [[ -n "${CONTEXT}" ]] && echo " [gcp: ${CONTEXT}]"
}

__kube_ps1()
{
    # If kubectl is not configured return empty string
    [[ -f ~/.kube/config ]] || return

    local CONTEXT=$(grep current-context ~/.kube/config | awk '{print $2}')
    local NS=$(kubectl config view --minify --output 'jsonpath={..namespace}')

    [[ -n "${CONTEXT}" ]] && echo " [k8s: ${CONTEXT}/${NS}]"
}

PS1='\[\e[1;32m\]\u@\h:\w\e[1;33m\]$(__git_ps1)\e[1;34m\]$(__gcloud_ps1)$(__kube_ps1)\e[1;32m\]\n$\[\e[0m\] '
PS2='> '
PS3='> '
PS4='+ '

export TERM=xterm-256color

# Source bash bookmarking tool
[ -f "$HOME/.dotfiles/to.sh" ] && source "$HOME/.dotfiles/to.sh"

# Source kubectl completion if kubectl is present
command -v kubectl > /dev/null && source <(kubectl completion bash)
command -v minikube > /dev/null && source <(minikube completion bash)
command -v helm > /dev/null && source <(helm completion bash)

# Shortcuts
alias v=vim
alias k=kubectl
command -v calc > /dev/null && alias c=calc
# g is a "smart" alias to git
#
# When invoked without arguments it shows status.
# With arguments it pass it to the git.
# 
# This shows git status
#   $ g 
#
# This shows log
#   $ g log
# 
# Works with git aliases.
function g() {
    if [[ $# -eq 0 ]]; then
        git status
    else
        git $@
    fi
}

# Add aws cli completion
command -v aws_completer > /dev/null && complete -C "$(which aws_completer)" aws

export GOPATH=$HOME/go
# export GOROOT=$HOME/soft/go
export PATH="$PATH:/usr/local/go/bin:$HOME/soft/go/bin:$GOPATH/bin:$HOME/.local/bin:$HOME/bin:/var/lib/snapd/snap/bin:${KREW_ROOT:-$HOME/.krew}/bin"

export PYTHONDONTWRITEBYTECODE=1
export FZF_DEFAULT_COMMAND='fd --type f'

# Configure google-auth python lib to use credentials from gcloud
# This is needed for ansible dynamic inventory
export GCP_AUTH_KIND=application

[ -f /etc/bash_completion ] && source /etc/bash_completion
[ -d ~/soft/ansible-completion ] && source ~/soft/ansible-completion/*.bash
[ -f ~/.bash_aliases ] && source ~/.bash_aliases
[ -f /usr/share/fzf/shell/key-bindings.bash ] && source /usr/share/fzf/shell/key-bindings.bash

[ -d .config/broot ] && source /home/avd/.config/broot/launcher/bash/br
