"	gVim configuration file 
"		by Alex Dzeban
"	
"		September 2, 2010

" GUI Font
set gfn=Inconsolata\ 9
"set gfn=Anonymous\ Pro\ 9
"set gfn=Liberation\ Mono\ 9

syntax enable
set background=dark
colorscheme tile


" Remove toolbar, menubar and scrollbars
set guioptions-=T
set guioptions-=m
set guioptions-=r
set guioptions-=R
set guioptions-=l
set guioptions-=L


" Enable mouse
set mouse=a
set mousemodel=popup


"Encodings menu
menu Encodings.koi8-r :e ++enc=koi8-r<CR>
menu Encodings.windows-1251 :e ++enc=cp1251<CR>
menu Encodings.cp866 :e ++enc=cp866<CR>
menu Encodings.utf-8 :e ++enc=utf8 <CR>

if has("gui_running")
  if has("autocmd")
    " Automatically resize splits when resizing MacVim window
    autocmd VimResized * wincmd =
  endif
endif
