# Config for homemaker - https://github.com/FooSoft/homemaker
# Invoke like this
#   homemaker -verbose homemaker.yaml .

tasks:
  default:
    links:
      - [.config/i3, .i3]
      - [.config/polybar/config.ini, polybar.ini]
      - [.config/dunst/dunstrc, dunstrc]
      - [.config/rofi/config.rasi, rofi.rasi]
      - [.tmux.conf]
      - [.vimrc]
      - [.gvimrc]
      - [.config/nvim, nvim]
      - [.inputrc]
      - [.gitignore]
      - [.agignore]
      - [.clang-format]
      - [.pylintrc, pylintrc]
      - [.bash_aliases]
      - [.ctags]
      - [.config/clipit/clipitrc, clipitrc]
      - [.config/redshift/redshift.conf, redshift.conf]
    templates:
      - [.gitconfig]
      - [.bashrc]
