---
# Reload kernel module for macbook keyboard to apply module params.
# Module is reloaded with `;` to always invoke modprobe even if module wasn't
# initially loaded for some reason.
- name: reload hid_apple
  shell: rmmod hid_apple; modprobe hid_apple
  become: yes
