---
- name: Ensure systemd service dir
  file:
    path: "{{ ansible_user_dir }}/.config/systemd/user"
    state: directory

- name: Render ssh-agent service
  copy:
    src: ssh-agent.service
    dest: "{{ ansible_user_dir }}/.config/systemd/user/ssh-agent.service"

- name: Enable and run ssh-agent service
  systemd:
    scope: user
    name: ssh-agent
    state: started
    enabled: yes
    daemon_reload: yes
