---

- name: Install Neovim packages
  become: yes
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - neovim
    - python2-neovim
    - python3-neovim

- name: Ensure config dir
  file:
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory

- name: Configure to use Vim config
  copy:
    src: files/init.vim
    dest: "{{ ansible_user_dir }}/.config/nvim/"