---

- name: Download Neovim appimage
  get_url:
    url: "{{ neovim_appimage_url }}"
    dest: "{{ neovim_appimage_path }}"
    mode: 0755
    force: yes

- name: Symlink nvim appimage
  file:
    state: link
    src: "{{ neovim_appimage_path }}"
    dest: "{{ neovim_bin }}"
    mode: 0755

- name: Ensure python modules
  pip:
    name: [pynvim, neovim]
    state: latest
    executable: "{{ item }}"
  loop:
    - pip2
    - pip3
  become: yes

- name: Ensure config dir
  file:
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory
