---

- name: Download Neovim appimage
  get_url:
    url: "{{ neovim_appimage_url }}"
    dest: "{{ neovim_appimage_path }}"
    mode: 0755
    force: yes
    timeout: 180

- name: Symlink nvim appimage
  file:
    state: link
    src: "{{ neovim_appimage_path }}"
    dest: "{{ neovim_bin }}"
    mode: 0755
  become: yes

- name: Ensure python modules
  pip:
    name: [pynvim, neovim]
    state: latest
  become: yes

- name: Ensure config dir
  file:
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory

- name: Install vim-plug
  shell: curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: Install plugins
  shell: vim +PlugUpgrade +PlugUpdate +PlugClean +qall
  no_log: true
