---

- name: Download Neovim appimage
  get_url:
    url: "{{ neovim_appimage_url }}"
    dest: "{{ neovim_dest_dir }}"
    mode: 0755

- name: Symlink nvim appimage
  file:
    state: link
    src: "{{ neovim_dest_dir }}/nvim.appimage"
    dest: "{{ neovim_bin }}"
    mode: 0755

- name: Ensure config dir
  file:
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory
