---
- name: Ensure path
  file:
    state: directory
    dest: "{{ neovim_dest_dir }}"

- name: Download Neovim appimage
  get_url:
    url: "{{ neovim_appimage_url }}"
    dest: "{{ neovim_appimage_path }}"
    mode: 0755
    force: yes
    timeout: 180

- name: Symlink nvim appimage
  file:
    state: link
    src: "{{ neovim_appimage_path }}"
    dest: "{{ neovim_bin }}"
    mode: 0755
  become: yes

- name: Ensure python modules
  command: python3 -m pip install --upgrade pynvim neovim
  when: ansible_distribution != "Ubuntu"

- name: Ensure config dir
  file:
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory
